### ISSUE TITLE
node-red-contrib-skyremote-new

### ISSUE THREAD

**Issue by ukmoose** [aSilentSniper/Shaewen-Chronicles#8]
Given you don’t have issues open for your node…

Not sure why you couldn’t have done a pull request rather than fork and republish the node.

But given you have, can you modify the Readme to explain the differences and also publish a way that anyone who has issues with your fork can contact you rather than me.

Many thanks

**Comment by aSilentSniper** [comment]
I have changed everything pointing to me an have left you in the copyright for the orignal code
